edu/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:course_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:course_id>/', views.cart_remove, name='cart_remove'),
]

edu/courses/api/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('courses/', views.CourseList.as_view(), name='course_lst'),
    path('courses/<int:pk>/', views.CourseDetail.as_view(), name='course_det'),
    path('subjects/', views.SubjectList.as_view(), name='subject_lst'),
    path('subjects/<int:pk>/', views.SubjectDetail.as_view(), name='subject_det'),
    path('categories/', views.CategoryList.as_view(), name='category_lst'),
    path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category_det'), 
    path('modules/', views.ModuleList.as_view(), name='module_lst'),
    path('modules/<int:pk>/', views.ModuleDetail.as_view(), name='module_det'),    
]

edu/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    #path('', views.CourseList.as_view(), name='course_lst'),
    #path('<int:pk>/', views.CourseDetail.as_view(), name='course_det'),
    #path('subjects/', views.SubjectList.as_view(), name='subject_list'),
    #path('subjects/<int:pk>/', views.SubjectDetail.as_view(), name='subject_det'),
    #path('categories/', views.CategoryList.as_view(), name='category_lst'),
    #path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category_det'),
    
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('suggestion-info/<slug:slug>/', views.suggestion_info, name='suggestion_info'),
    path('search-results/', views.CourseSearchView.as_view(), name='search_results'),
    #path('', views.category_menu, name='category-list'),
    #path('', views.CategoryListView.as_view(), name='category_list'),
    path('about/', views.AboutListView.as_view(), name='about'),
    path('team/', views.TeamListView.as_view(), name='team'),
    path('reviews/', views.ReviewsListView.as_view(), name='reviews'),
    path('404/', views.NotFoundListView.as_view(), name='404'),
    path('contact/', views.contact, name='contact'),
    path('', views.courses_count_and_best, name='courses_count'),
    path('corcount/', views.courses_count_and_best, name='courses_count'),
    
    path('category/<slug>/', views.CategoryDetailView.as_view(), name='category-detail'),
    #path('', views.SubjectListView.as_view(), name='subject_list'),
    #path('accounts/profile/', views.SubjectListView_P.as_view(), name='account-profile'),
    path('accounts/profile/', views.OrdersUnpaidByUserListView.as_view(), name='account-profile'),
    path('accounts/profile/name-change/', views.name_change_form, name='name-change'),
    path('accounts/profile/imageupload/', views.image_upload, name='image-upload'),
    path('subject/<slug>/', views.SubjectDetailView.as_view(), name='subject-detail'),
    #path('accounts/profile/', user_profile, name='account-profile')
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('module/order/', views.ModuleOrderView.as_view(), name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_list_subject'),
    
    path('course/<int:pk>/', views.CourseRateDetaillView.as_view(), name='course_rate_detail'),
    
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    #path('course/<slug:slug>/', views.course_detail, name='course_detail'), 
    
    #path('course/<int:pk>/', views.CourseRateDetaillView.as_view(), name='course_rate_detail'),
    
    path('course_review/course/<int:pk>/', views.review_course, name='course_review'), 
    
    path('course_ratings/course/<int:pk>/', views.course_detail_review, name='course_detail_review'), 
    
]

edu/edu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from courses.views import CourseListView
#import debug_toolbar
from django.conf.urls.i18n import i18n_patterns
from dj_rest_auth.views import PasswordResetView, PasswordResetConfirmView

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), 
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('courses.urls', namespace='courses')),  
    path('students/', include('students.urls')),
    path(('users/'), include('users.urls')),
    path('password-reset/', PasswordResetView.as_view()),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# else:
#    urlpatterns += staticfiles_urlpatterns()

edu/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.order_create, name='order_create'),
path('mycourses/', views.OrdersCurrentUserView.as_view(), name='student_course_list'),
path('course/<int:pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
path('course/<int:pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
path('unpaidorderlist/', views.OrdersUnpaidByUserListView.as_view(), name='unpaid_order_list'),
path('unpaidorderlist/order/<int:pk>/', views.OrdersByUserDetailView.as_view(), name='unpaid_order_detail'),
path('unpaidorder/<int:order_id>/', views.unpaid_order_process, name='unpaid_order_process'),
path('unpaidorder/<int:order_id>/deleted/', views.unpaid_order_delete, name='unpaid_order_delete'),
]

edu/courses/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .fields import OrderField
from django.shortcuts import reverse
from django.template.loader import render_to_string
from django.db.models import Avg, Count
from django.utils.translation import gettext_lazy as _
#from parler.models import TranslatableModel, TranslatedFields


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

def course_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/course_<id>/<filename>
    return 'course_{0}/{1}'.format(instance.course.id, filename)


class Category(models.Model):
    title = models.CharField(_('category title'), max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def countsubjects(self):
        #course_cnt = Course.objects.filter(subject__category).all()   #aggregate(count=Count('id'))
        subject_cnt = Subject.objects.annotate(total_subjects=Count('subject'))
        cnt=0
        if subject_cnt["count"] is not None:
            cnt = int(subject_cnt["count"])
        return cnt

    def get_absolute_url(self):
        """Returns the url to access a particular category instance."""
        return reverse('courses:category-detail', args=[str(self.id)])


class Subject(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    title = models.CharField(_('subject title'), max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['category']   # 'title'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular subject instance."""
        return reverse('courses:subject-detail', args=[str(self.id)])


class Course(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name='courses_created',
                              on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject,
                                on_delete=models.CASCADE)  #related_name='courses',
    title = models.CharField(_('course title'), max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, through='StudentCourses',
                                      related_name='courses_joined', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(default='no_image.png',
                              upload_to='images')
    hours = models.DecimalField(max_digits=4, decimal_places=2, default=0)

    class Meta:
        ordering = ['title']  #  title -created
        # index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def averagereview(self):
        review = Review.objects.filter(course=self).aggregate(average=Avg('rate'))
        avg=0
        if review["average"] is not None:
            avg=float(review["average"])
        return avg

    def countreview(self):
        reviews = Review.objects.filter(course=self).aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular course instance."""
        return reverse('courses:course_detail', kwargs={'slug': self.slug}) #args=[str(self.id)]

    def get_suggestion_url(self):
        return f"/suggestion-info/{self.slug}/"


class StudentCourses(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    #class Meta:
        #verbose_name_plural = 'Ordered Items'
        #unique_together = ['order', 'orderitem']


class Module(models.Model):
    course = models.ForeignKey(Course,
                               related_name='modules',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])

    def __str__(self):
        return f'{self.order}. {self.title}'

    class Meta:
        ordering = ['order']


class Content(models.Model):
    module = models.ForeignKey(Module,
                               related_name='contents',
                               on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in':(
                                     'text',
                                     'video',
                                     'image',
                                     'file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string(f'courses/content/{self._meta.model_name}.html',
                                {'item': self})

class Text(ItemBase):
    content = models.TextField()

class File(ItemBase):
    file = models.FileField(upload_to='files')

class Image(ItemBase):
    file = models.FileField(upload_to='images')

class Video(ItemBase):
    url = models.URLField()

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    image = models.ImageField(default='default.png',
                              upload_to=user_directory_path)

    def __str__(self):
        # return self.user.username
        return f'{self.user.username} UserProfile'


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length = 100, null=True, blank=True)
    comment = models.TextField(max_length=300, null=True, blank=True)
    rate = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    #class Meta:
    #    unique_together = ['user', 'course']

    def __str__(self):
        return str(self.id)

edu/courses/api/views.py
from rest_framework import generics
from ..models import Subject, Course, Module, Content, UserProfile, Category, Review
from .serializers import CourseSerializer, CourseDetailSerializer, SubjectSerializer, SubjectDetailSerializer,CategorySerializer, CategoryDetailSerializer, ModuleSerializer


class CourseList(generics.ListCreateAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

class CourseDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseDetailSerializer

class SubjectList(generics.ListCreateAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer 

class SubjectDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectDetailSerializer
    
class CategoryList(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer   

class CategoryDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoryDetailSerializer

class ModuleList(generics.ListAPIView):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer

class ModuleDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer
    

edu/courses/templates/category_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ category.title }} category courses:</h2>

    {% for cat in category.subject_set.all %}

        <p><strong>&nbsp;&nbsp;Subject title: <a href="{% url 'courses:subject-detail' cat.slug %}" id="{{ cat.id }}"> {{ cat.title }}</strong></p></a>
        {% for sub in cat.course_set.all %}
	    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Course: &nbsp;&nbsp;<a href="{% url 'courses:course_detail' sub.slug %}" id="{{ sub.id }}">{{ sub.title }}</p></a>
	 {% endfor %}
    {% endfor %}

{% endblock content %}

edu/courses/templates/footer.html
{% load static %}

<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-4 mt-5 wow fadeIn" data-wow-delay="0.1s">  <!--pt-3 mt-5 -->
    <div class="container py-3">  <!--py-5-->
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-3">Company</h5>
                <a class="btn btn-link" href="{% url 'courses:about' %}">About Us</a>
                <a class="btn btn-link" href="{% url 'courses:contact' %}">Contact Us</a>
                <a class="btn btn-link" href="">Terms & Conditions</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-3">Teaching</h5>
                <a class="btn btn-link" href="{% url 'courses:contact' %}">Become a Teacher</a>
                <a class="btn btn-link" href="">How to Guide</a>
                <a class="btn btn-link" href="">Terms & Conditions</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-3">Community</h5>
                <a class="btn btn-link" href="">Documentation</a>
                <a class="btn btn-link" href="">Forum</a>
                <a class="btn btn-link" href="">FAQs</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-3">Contact Information</h5>
                <p class="mb-2">201 Mission St. San Francisco, CA, USA</p>  <!--<i class="fa fa-map-marker-alt me-3"></i>-->
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+1 415 898-5555</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@edu.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-instagram"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>            
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy;2024 <a href="#">EDU</a>, All Rights Reserved.
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="/">Home</a>
                        <a href="{% url 'courses:course_list' %}">Courses</a>
                        <a href="">Help</a>
                        <a href="">FAQs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

edu/courses/templates/navbar.html
    {% load navmenu %}
    {% load i18n %}
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg navbar-dark shadow sticky-top p-0" style="background-color: #1C2140;">  <!--style="background-color: #1C2140;"  #05BECB-->
        <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <strong class="m-0 text-primary"><i class="fa fa-user-graduate me-3"></i>EDU</strong>
        </a>
        <ul class="navbar-nav ms-auto p-4 p-lg-0">
            <li class="nav-item dropdown">   <!-- "nav-item dropdown" div -->
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color:#fff" aria-expanded="false">{% trans "Categories" %}</a>
                        <!--<div class="dropdown-menu fade-down m-0"> -->
                            <!-- for cat in categoryitems %} -->
                            <!-- <p><a href="{{ category.get_absolute_url }}" class="dropdown-item">{{ cat.title }}</a></p> -->
                            <!--    <p><a class="dropdown-item">{{ cat.title }} </a></p> style="background-color: #8080EB; style="color:#fff"-->
                            <!--     for s in cat.subject_set.all %}
                                    <p><a class="dropdown-item">{{ s.title }}</a></p>
                                    endfor%} -->
                        <!--   endfor%} 
                        </div> -->
                        {% cat_menu %}                
            </li> 
            {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" style="color:#fff" href="{% url 'courses:account-profile' %}">{% trans "Profile" %}</a>
                <a class="nav-item nav-link" href="{% url 'account_logout' %}" style="color:#fff">{% trans "Logout" %}</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'account_login' %}" style="color:#fff">{% trans "Login" %}</a>
            {% endif %}
            
            <!--Django search start-->
            <form class="form-inline" action="{% url 'courses:search_results' %}" method="get">
                <div class="input-group">  
                    <input class="form-control mr-sm-2" type="text" placeholder="{% trans 'Search courses' %}" aria-label="Search" name="search_courses">
                    <button type="submit" class="btn btn-outline-primary"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!--Django search end-->
            
        </ul>

        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">  <!-- collapse navbar-collapse -->           
            <ul class="navbar-nav ms-auto p-4 p-lg-0">  <!-- div -->
                
                <a href="/" style="color:#fff" class="nav-item nav-link">{% trans "Home" %}</a>  <!--active-->
                <a href="{% url 'courses:about' %}" class="nav-item nav-link" style="color:#fff">{% trans "About" %}</a>

                

                
                {% if request.user.is_authenticated %}

                    {% if user.groups.all.0.name == 'Instructors' %}
                    {% else %}
                        {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            <a class="nav-item nav-link" href="{% url 'cart:cart_detail' %}" style="color:#fff">
                                Cart <span class="text-danger">${{ cart.get_total_price }}</span>
                                <span class="text-primary"> ({{ total_items }})</span>
                            </a> <!--item{{ total_items|pluralize }}-->      
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'cart:cart_detail' %}" style="color:#fff">{% trans "Cart" %} <span class="text-danger">(0)</span></a>
                        {% endif %}
                        {% endwith %}
                    {% endif %}

                {% else %}
                    <a class="nav-item nav-link" href="{% url 'account_signup' %}" style="color:#fff">{% trans "Signup" %}</a>
                {% endif %}

                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color:#fff">{% trans "Pages" %}</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="{% url 'courses:team' %}" class="dropdown-item">{% trans "Our Team" %}</a>
                        <a href="{% url 'courses:reviews' %}" class="dropdown-item">{% trans "Reviews" %}</a>
                        <a href="{% url 'courses:404' %}" class="dropdown-item">{% trans "404 Page" %}</a>
                    </div>
                </div>
                <a href="{% url 'courses:contact' %}" class="nav-item nav-link" style="color:#fff">{% trans "Contact" %}</a>

                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% get_language_info for LANGUAGE_CODE as lang %}

            <div class="nav-item dropdown">
            
                {% if LANGUAGE_CODE == 'en' %}
                    {% with icon_code='us' %}
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="dropdown09"
                        ><span class="flag-icon flag-icon-{{ icon_code }}"> </span>  <!--aria-haspopup="true" aria-expanded="false" -->
                        {{ lang.name }}</a> 
                    {% endwith %}

                    <div class="dropdown-menu" aria-labelledby="dropdown09">
                        {% for language in languages %}  
                            {% if language.code == LANGUAGE_CODE %} 
                                <!-- skip the active language -->   
                            {% else %}
                                <a class="dropdown-item" href="/{{ language.code }}/"><span class="flag-icon flag-icon-{{ language.code }}"> </span> {{ language.name }}</a>    
                            {% endif %}
                        {% endfor %}
                    </div>
                {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="dropdown09"
                        ><span class="flag-icon flag-icon-{{ lang.code }}"> </span>  <!--aria-haspopup="true" aria-expanded="false" -->
                        {{ lang.name }}</a> 

                    <div class="dropdown-menu" aria-labelledby="dropdown09">
                        {% for language in languages %} 
                            {% if language.code == LANGUAGE_CODE %}  
                                <!-- skip the active language --> 
                            {% else %}   
                                {% if language.code == 'en' %}
                                    {% with icon_code='us' %}
                                    <a class="dropdown-item" href="/{{ language.code }}/"><span class="flag-icon flag-icon-{{ icon_code }}"> </span> {{ language.name }}</a> 
                                    {% endwith %}
                                {% else %}
                                    <a class="dropdown-item" href="/{{ language.code }}/"><span class="flag-icon flag-icon-{{ language.code }}"> </span> {{ language.name }}</a>
                                {% endif %}

                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}    
            </div>    

            </ul> 
            
            

            {% comment %}
            <div class="nav-item dropdown">
                {% if LANGUAGE_CODE == 'en' %}
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="dropdown09"
                        ><span class="flag-icon flag-icon-us"> </span>  <!--aria-haspopup="true" aria-expanded="false" -->
                        English</a>   
                    <div class="dropdown-menu" aria-labelledby="dropdown09">
                        <a class="dropdown-item" href="/ru/"><span class="flag-icon flag-icon-ru"> </span> Russian</a>  <!--class="dropdown-item"-->
                    </div>
                {% else %}
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="dropdown09"
                        ><span class="flag-icon flag-icon-ru"> </span>  <!--aria-haspopup="true" aria-expanded="false" -->
                        Russian</a>   
                    <div class="dropdown-menu" aria-labelledby="dropdown09">
                        <a class="dropdown-item" href="/en/"><span class="flag-icon flag-icon-us"> </span> English</a> 
                    </div>  
                {% endif %}
            </div>
            {% endcomment %}

        </div>
    </nav>
    <!-- Navbar End -->

edu/courses/templates/subject_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ subject.title }} subject courses:</h2>

    {% for cor in subject.course_set.all %}
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Course:<a href="{% url 'courses:course_detail' cor.slug %}" id="{{ cor.id }}">&nbsp;&nbsp;{{ cor.title }}</p></a>
    {% endfor %}
{% endblock content %}