edu/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:course_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:course_id>/', views.cart_remove, name='cart_remove'),
]

edu/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

edu/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    #path('', views.CourseList.as_view(), name='course_lst'),
    #path('<int:pk>/', views.CourseDetail.as_view(), name='course_det'),
    #path('subjects/', views.SubjectList.as_view(), name='subject_list'),
    #path('subjects/<int:pk>/', views.SubjectDetail.as_view(), name='subject_det'),
    #path('categories/', views.CategoryList.as_view(), name='category_lst'),
    #path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category_det'),
    
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('suggestion-info/<slug:slug>/', views.suggestion_info, name='suggestion_info'),
    path('search-results/', views.CourseSearchView.as_view(), name='search_results'),
    #path('', views.category_menu, name='category-list'),
    #path('', views.CategoryListView.as_view(), name='category_list'),
    path('about/', views.AboutListView.as_view(), name='about'),
    path('team/', views.TeamListView.as_view(), name='team'),
    path('reviews/', views.ReviewsListView.as_view(), name='reviews'),
    path('404/', views.NotFoundListView.as_view(), name='404'),
    path('contact/', views.contact, name='contact'),
    path('', views.courses_count_and_best, name='courses_count'),
    path('corcount/', views.courses_count_and_best, name='courses_count'),
    
    path('category/<slug>/', views.CategoryDetailView.as_view(), name='category-detail'),
    #path('', views.SubjectListView.as_view(), name='subject_list'),
    #path('accounts/profile/', views.SubjectListView_P.as_view(), name='account-profile'),
    path('accounts/profile/', views.OrdersUnpaidByUserListView.as_view(), name='account-profile'),
    path('accounts/profile/name-change/', views.name_change_form, name='name-change'),
    path('accounts/profile/imageupload/', views.image_upload, name='image-upload'),
    path('subject/<slug>/', views.SubjectDetailView.as_view(), name='subject-detail'),
    #path('accounts/profile/', user_profile, name='account-profile')
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('module/order/', views.ModuleOrderView.as_view(), name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_list_subject'),
    
    path('course/<int:pk>/', views.CourseRateDetaillView.as_view(), name='course_rate_detail'),
    
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    #path('course/<slug:slug>/', views.course_detail, name='course_detail'), 
    
    #path('course/<int:pk>/', views.CourseRateDetaillView.as_view(), name='course_rate_detail'),
    
    path('course_review/course/<int:pk>/', views.review_course, name='course_review'), 
    
    path('course_ratings/course/<int:pk>/', views.course_detail_review, name='course_detail_review'), 
    
]

edu/edu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from courses.views import CourseListView
#import debug_toolbar
from django.conf.urls.i18n import i18n_patterns
from dj_rest_auth.views import PasswordResetView, PasswordResetConfirmView

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), 
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('courses.urls', namespace='courses')),  
    path('students/', include('students.urls')),
    path(('users/'), include('users.urls')),
    path('password-reset/', PasswordResetView.as_view()),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# else:
#    urlpatterns += staticfiles_urlpatterns()

edu/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.order_create, name='order_create'),
path('mycourses/', views.OrdersCurrentUserView.as_view(), name='student_course_list'),
path('course/<int:pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
path('course/<int:pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
path('unpaidorderlist/', views.OrdersUnpaidByUserListView.as_view(), name='unpaid_order_list'),
path('unpaidorderlist/order/<int:pk>/', views.OrdersByUserDetailView.as_view(), name='unpaid_order_detail'),
path('unpaidorder/<int:order_id>/', views.unpaid_order_process, name='unpaid_order_process'),
path('unpaidorder/<int:order_id>/deleted/', views.unpaid_order_delete, name='unpaid_order_delete'),
]

edu/cart/models.py
from django.db import models

# Create your models here.

edu/cart/forms.py
from django import forms


COURSE_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddCourseForm(forms.Form):
    #quantity = forms.TypedChoiceField(choices=COURSE_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

edu/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from courses.models import Course
from .cart import Cart
from .forms import CartAddCourseForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, course_id):
    cart = Cart(request)
    course = get_object_or_404(Course, id=course_id)
    form = CartAddCourseForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(course=course,
                 override_quantity=cd['override']) #quantity=cd['quantity'],
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, course_id):
    cart = Cart(request)
    course = get_object_or_404(Course, id=course_id)
    cart.remove(course)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddCourseForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

edu/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Shopping cart</h1>
  <table class="cart">   <!--cart-->
    <thead>
      <tr>
        <th>Image</th>
        <th>Course</th>
        <!--<th>Quantity</th> -->
        <th>Remove</th>
        <!--<th>Item price</th> -->
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with course=item.course %}
          <tr>
            <td>
              <a href="{{ course.get_absolute_url }}">
                <img src="{% if course.image %}{{ course.image.url }}{% else %}{% static 'no_image.png' %}{% endif %}" 
                  class="img-fluid" style="width:50px;hight=50px;">
              </a>
            </td>
            <td><h4>{{ course.title }}</h4></td>
            <!--<td>
              <form action="{% url 'cart:cart_add' course.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td> -->
            <td>
              <form action="{% url 'cart:cart_remove' course.id %}" method="post">
                <input type="submit" value="Remove">  <!--class="img-fluid" style="width:30%"-->
                {% csrf_token %}
              </form>
            </td>
            <td>${{ item.price }}</td>  <!-- class="num" -->
            <!--<td class="num">${{ item.total_price }}</td> -->
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            "{{ cart.coupon.code }}" coupon
            ({{ cart.coupon.discount }}% off)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>

  <p>Apply a coupon:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
  </form>

  <p class="text-right">
    <a href="{% url 'courses:course_list' %}" class="button light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
  </p>
{% endblock %}