edu/edu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from courses.views import CourseListView
#import debug_toolbar
from django.conf.urls.i18n import i18n_patterns
from dj_rest_auth.views import PasswordResetView, PasswordResetConfirmView

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), 
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('courses.urls', namespace='courses')),  
    path('students/', include('students.urls')),
    path(('users/'), include('users.urls')),
    path('password-reset/', PasswordResetView.as_view()),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# else:
#    urlpatterns += staticfiles_urlpatterns()

edu/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.order_create, name='order_create'),
path('mycourses/', views.OrdersCurrentUserView.as_view(), name='student_course_list'),
path('course/<int:pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
path('course/<int:pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
path('unpaidorderlist/', views.OrdersUnpaidByUserListView.as_view(), name='unpaid_order_list'),
path('unpaidorderlist/order/<int:pk>/', views.OrdersByUserDetailView.as_view(), name='unpaid_order_detail'),
path('unpaidorder/<int:order_id>/', views.unpaid_order_process, name='unpaid_order_process'),
path('unpaidorder/<int:order_id>/deleted/', views.unpaid_order_delete, name='unpaid_order_delete'),
]

edu/orders/models.py
from django.db import models
from django.conf import settings
from courses.models import Course
from django.shortcuts import reverse
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)
    coupon = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'
        #f'Order {self.id}' + ' ' + self.user.first_name + ' ' + self.user.last_name + ' ' + self.user.email

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        t_cost = total_cost - total_cost * (self.discount / Decimal(100))
        return round(Decimal(t_cost), 2)
        #return sum(item.get_cost() for item in self.items.all())

    def get_absolute_url(self):
        """Returns the url to access a particular subject instance."""
        return reverse('courses:course_detail', args=[str(self.id)])


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    course = models.ForeignKey(Course,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    #quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.course.price   # self.quantity

edu/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['user', 'created', 'updated', 'paid', 'braintree_id', 'coupon', 'discount']

edu/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from .models import OrderItem, Order
from courses.models import Course, Module, StudentCourses
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from .tasks import order_created
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages



@login_required
def order_create(request):
    cart = Cart(request)
    
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user 
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
               
            for item in cart:
                course = item['course']
                OrderItem.objects.create(order=order, course=item['course']) 
                course.students.add(request.user)
                #StudentCourses.objects.create(user=request.user, course=item['course']) 
                # clear the cart
                cart.clear()
                # launch asynchronous task (run Celery in different shell: celery -A edu worker -l info)
                order_created.delay(order.id)
                # set the order in the session
                request.session['order_id'] = order.id
                # redirect for payment
            return redirect(reverse('payment:process'))
            #return render(request, 'orders/order/created.html', {'order': order})   
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})   


class OrdersUnpaidByUserListView(LoginRequiredMixin, ListView):
    model = Order
    # context_object_name = 'orders_list_by_user'
    template_name = 'orders/order/unpaid_order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, paid=False).order_by('-created')


class OrdersByUserDetailView(LoginRequiredMixin, DetailView):
    """Generic class-based view listing items for current order of current user."""
    model = Order
    template_name = 'orders/order/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ordid = self.object.pk
        context['orderitems'] = OrderItem.objects.filter(
            order__user=self.request.user, order_id=ordid)
        return context

class OrdersPaidByUserDetailView(LoginRequiredMixin, DetailView):
    """Generic class-based view listing items for current order of current user."""
    model = Order
    template_name = 'orders/order/paid_order_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ordid = self.object.pk
        context['paidorderitems'] = OrderItem.objects.filter(
            order__user=self.request.user, order_id=ordid)
        return context

@login_required
def unpaid_orders(request, order_id):
    order = get_object_or_404(Order, id=order_id, paid=False)
    orderitems = OrderItem.objects.filter(order=order, order__user=request.user)    
    return render(request, 'orders/order/unpaid_order_list.html', {'orderitems': orderitems})


@login_required
def unpaid_order_delete(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    orderitems = OrderItem.objects.filter(order=order, order__user=request.user) 
    print("Order: ", order)
    print("Orderitems: ", orderitems)
    for item in orderitems:
        course = item.course
        print("Course ID: ", course.id)
        course.students.remove(request.user)   
        #Course.objects.filter(id=course.id).update(student=None)
    order.delete()
    return render(request, 'orders/order/unpaid_order_deleted.html', {'orderitems': orderitems})


@login_required
def unpaid_order_process(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    orderitems = OrderItem.objects.filter(order=order, order__user=request.user)
    if order:
        request.session['order_id'] = order.id
        return redirect(reverse('payment:process'))
    return render(request, 'orders/order/process_unpaid_order.html', {'orderitems': orderitems})


class OrdersCurrentUserView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'mycourses/ordered_courses.html'
    # paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # OrdersCurrentUserView,self
        uid = self.request.user
        context['orderitems'] = OrderItem.objects.filter(
            order__user=self.request.user, order__paid=True).order_by('order_id')
        context['unpaidorderitems'] = OrderItem.objects.filter(
            order__user=self.request.user, order__paid=False).order_by('order_id')
        return context


class StudentCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'orders/order/course/course_detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paid_courses = OrderItem.objects.filter(order__user=self.request.user.id, order__paid=True) 
        course = self.get_object()
        print('Course object ID: ', course.id)
        for m in paid_courses:
            print('Paid object ID: ', m.course_id)
            if course.id == m.course_id:       
                print('After if course object ID: ', course.id, ' Paid object ID: ', m.course_id)
                if 'module_id' in self.kwargs:
                # get current module
                    context['module'] = course.modules.get(
                                        id=self.kwargs['module_id'])
                else:
                    # get first module
                    context['module'] = course.modules.all().first()   #[0]
                    print(context)
                return context
        else:
            raise Http404('Sorry. You did not pay for this course.')


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})

    

edu/orders/templates/orders/order/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}
  <h1>Checkout</h1>

  <div class="order-info">
    <h3>Your order</h3>
    <ul>
      {% for item in cart %}
        <li>
          {% comment %}{{ item.quantity }}x{% endcomment %} {{ item.course.title }}
          <span>${{ item.total_price|floatformat:2 }}</span>
        </li>
      {% endfor %}
      {% if cart.coupon %}
        <li>
          "{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% off)
          <span class="neg">- ${{ cart.get_discount|floatformat:2 }}</span>
        </li>
      {% endif %}
    </ul>
    <p>Total: ${{ cart.get_total_price_after_discount|floatformat:2 }}</p>
    
  </div>

  <form method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
  </form>
  
{% endblock %}

edu/orders/templates/orders/order/created.html
{% extends "base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}
  <h1>Thank you</h1>
  <p>Your order has been successfully completed. Your order number is
  <strong>{{ order.id }}</strong>.</p>
{% endblock %}

edu/orders/templates/orders/order/order_detail.html
{% extends "base.html" %}

{% block title %}Order details{% endblock %}

{% block content %}

    <div class="container-fluid">
        {% if orderitems %}
        <div class="table-responsive text-nowrap">

            <h2 style="font-weight:bold;text-align:center;">Details for order {{ order.id }}:</h2>
            
            <div class="row">
                <div class="col">
                    <table class="table">
                        <thead class="table-primary">
                            <tr>
                                <th scope="col" style="background-color: #1C2140;">#</th>
                                <th scope="col" style="background-color: #1C2140;">Logo</th>
                                <th scope="col" style="background-color: #1C2140;">Course Title</th>
                                <th scope="col" style="background-color: #1C2140;">Price</th>
                            </tr>
                        </thead>
                        <tbody>

                        {% for it in orderitems %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td><img src="{{ it.course.image.url }}" class="img-fluid" alt="" style="width:10%"></td>
                                <td>{{ it.course.title }}</td>
                                <td>${{ it.course.price }}</td>                                
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>                
            </div>
        {% else %}
            <h2 style="font-weight:bold;text-align:center">You have no unpaid courses {{ user.username }}</h2>   
        {% endif %} 
    </div>

{% endblock content %}

edu/orders/templates/orders/order/process_unpaid_order.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Checkout unpaid order
{% endblock %}

{% block content %}
  <h1>Checkout unpaid order</h1>

  <div class="order-info">
    <h3>Your order</h3>
    <ul>
      {% for item in orderitems %}
        <li>
          {{ item.quantity }}x {{ item.course.title }}
          <span>${{ item.total_price|floatformat:2 }}</span>
        </li>
      {% endfor %}
      

  <form method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
  </form>
  
{% endblock %}

edu/orders/templates/orders/order/unpaid_order_deleted.html
{% extends "base.html" %}

{% block title %}
  Unpaid Order Deleted
{% endblock %}

{% block content %}
  <p>Your unpaid order has been successfully deleted.</strong>.</p>
{% endblock %}

edu/orders/templates/orders/order/unpaid_order_list.html
{% extends "base.html" %}

{% block title %}Unpaid orders list{% endblock %}

{% block content %}

    <div class="container-fluid">
        {% if order_list %}
        <div class="table-responsive text-nowrap">

            <h2 style="font-weight:bold;text-align:center;">These are your unpaid orders {{ user.username }}:</h2>
            
            <div class="row">
                <div class="col">
                    <table class="table">
                        <thead class="table-primary">
                            <tr>
                                <th scope="col" style="background-color: #1C2140;">#</th>
                                <th scope="col" style="background-color: #1C2140;">Order Date</th>
                                <th scope="col" style="background-color: #1C2140;">Order ID</th>
                                <th scope="col" style="background-color: #1C2140;">Total Amount</th>
                                <th scope="col" style="background-color: #1C2140;">Order Details</th>
                                <th scope="col" style="background-color: #1C2140;">Make Payment</th>                        
                            </tr>
                        </thead>
                        <tbody>

                        {% for ord in order_list %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ ord.created }}</td>
                                <td>{{ ord.id }}</td>
                                <td>${{ ord.get_total_cost }}</td>
                                <td><a href="{% url 'orders:order_detail' ord.id%}" style="color: #0065cc">Click here to view details</a></td>
                                <td><a href="{% url 'orders:unpaid_order_process' ord.id %}"><button type="button" class="btn btn-dark">Pay Now</button></a></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <h2 style="font-weight:bold;text-align:center">You have no unpaid orders {{ user.username }}</h2>   
        {% endif %} 
    </div>

{% endblock content %}