edu/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:course_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:course_id>/', views.cart_remove, name='cart_remove'),
]

edu/courses/api/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('courses/', views.CourseList.as_view(), name='course_lst'),
    path('courses/<int:pk>/', views.CourseDetail.as_view(), name='course_det'),
    path('subjects/', views.SubjectList.as_view(), name='subject_lst'),
    path('subjects/<int:pk>/', views.SubjectDetail.as_view(), name='subject_det'),
    path('categories/', views.CategoryList.as_view(), name='category_lst'),
    path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category_det'), 
    path('modules/', views.ModuleList.as_view(), name='module_lst'),
    path('modules/<int:pk>/', views.ModuleDetail.as_view(), name='module_det'),    
]

edu/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    #path('', views.CourseList.as_view(), name='course_lst'),
    #path('<int:pk>/', views.CourseDetail.as_view(), name='course_det'),
    #path('subjects/', views.SubjectList.as_view(), name='subject_list'),
    #path('subjects/<int:pk>/', views.SubjectDetail.as_view(), name='subject_det'),
    #path('categories/', views.CategoryList.as_view(), name='category_lst'),
    #path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category_det'),
    
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('suggestion-info/<slug:slug>/', views.suggestion_info, name='suggestion_info'),
    path('search-results/', views.CourseSearchView.as_view(), name='search_results'),
    #path('', views.category_menu, name='category-list'),
    #path('', views.CategoryListView.as_view(), name='category_list'),
    path('about/', views.AboutListView.as_view(), name='about'),
    path('team/', views.TeamListView.as_view(), name='team'),
    path('reviews/', views.ReviewsListView.as_view(), name='reviews'),
    path('404/', views.NotFoundListView.as_view(), name='404'),
    path('contact/', views.contact, name='contact'),
    path('', views.courses_count_and_best, name='courses_count'),
    path('corcount/', views.courses_count_and_best, name='courses_count'),
    
    path('category/<slug>/', views.CategoryDetailView.as_view(), name='category-detail'),
    #path('', views.SubjectListView.as_view(), name='subject_list'),
    #path('accounts/profile/', views.SubjectListView_P.as_view(), name='account-profile'),
    path('accounts/profile/', views.OrdersUnpaidByUserListView.as_view(), name='account-profile'),
    path('accounts/profile/name-change/', views.name_change_form, name='name-change'),
    path('accounts/profile/imageupload/', views.image_upload, name='image-upload'),
    path('subject/<slug>/', views.SubjectDetailView.as_view(), name='subject-detail'),
    #path('accounts/profile/', user_profile, name='account-profile')
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('module/order/', views.ModuleOrderView.as_view(), name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_list_subject'),
    
    path('course/<int:pk>/', views.CourseRateDetaillView.as_view(), name='course_rate_detail'),
    
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    #path('course/<slug:slug>/', views.course_detail, name='course_detail'), 
    
    #path('course/<int:pk>/', views.CourseRateDetaillView.as_view(), name='course_rate_detail'),
    
    path('course_review/course/<int:pk>/', views.review_course, name='course_review'), 
    
    path('course_ratings/course/<int:pk>/', views.course_detail_review, name='course_detail_review'), 
    
]

edu/edu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from courses.views import CourseListView
#import debug_toolbar
from django.conf.urls.i18n import i18n_patterns
from dj_rest_auth.views import PasswordResetView, PasswordResetConfirmView

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), 
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('courses.urls', namespace='courses')),  
    path('students/', include('students.urls')),
    path(('users/'), include('users.urls')),
    path('password-reset/', PasswordResetView.as_view()),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# else:
#    urlpatterns += staticfiles_urlpatterns()

edu/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    #path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
    #path('course/<pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
]

edu/courses/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Course, Module, UserProfile, Review
from allauth.account.forms import SignupForm
from django.contrib.auth.models import User


ModuleFormSet = inlineformset_factory(Course,
                                      Module,
                                      fields=['title',
                                              'description'],
                                      extra=2,
                                      can_delete=True)
                                      

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user
        

class ChangeUserFnameLname(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        labels = {'first_name': 'First name', 'last_name': 'Last name'}


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class SearchForm(forms.Form):
    query = forms.CharField(
        label="Search",
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'search-input', 'placeholder': 'Search...'})
    )
    

class EmailContactForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)


#CHOICES = [('1','One Star'),('2','Two Stars'),('3','Three Stars'),('4','Four Stars'),('5','Five Stars'),]
RATE_CHOICES = (('1','One Star'), ('2','Two Stars'), ('3','Three Stars'), ('4','Four Stars'), ('5','Five Stars'))

class CourseReviewForm(forms.Form):
    #CHOICES = (('1','One Star'),('2','Two Stars'),('3','Three Stars'),('4','Four Stars'),('5','Five Stars'),)
    #course = forms.ModelChoiceField(queryset=Course.objects.all(), widget=forms.HiddenInput)
    #rate = forms.IntegerField(required=True)
    rate = forms.TypedChoiceField(label='Please rate this course', choices=RATE_CHOICES, widget=forms.RadioSelect, coerce=int, required=True)
    subject = forms.CharField(max_length = 100, required=False)
    comment = forms.CharField(max_length=300, widget=forms.Textarea, required=False)

edu/courses/api/views.py
from rest_framework import generics
from ..models import Subject, Course, Module, Content, UserProfile, Category, Review
from .serializers import CourseSerializer, CourseDetailSerializer, SubjectSerializer, SubjectDetailSerializer,CategorySerializer, CategoryDetailSerializer, ModuleSerializer


class CourseList(generics.ListCreateAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

class CourseDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseDetailSerializer

class SubjectList(generics.ListCreateAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer 

class SubjectDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectDetailSerializer
    
class CategoryList(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer   

class CategoryDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoryDetailSerializer

class ModuleList(generics.ListAPIView):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer

class ModuleDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer
    

edu/courses/templates/courses/course/course_rating_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <h4>Current ratings of {{ course_detail_review.title }} course:</h4> 

            <div class="review-feedback">
                <span class="fa fa-star" {% if course_detail_review.averagereview > 0 %} style='color: #f3da35' {% endif %}></span>
                <span class="fa fa-star" {% if course_detail_review.averagereview > 1 %} style='color: #f3da35' {% endif %}"></span>
                <span class="fa fa-star" {% if course_detail_review.averagereview > 2 %} style='color: #f3da35' {% endif %}"></span>
                <span class="fa fa-star" {% if course_detail_review.averagereview > 3 %} style='color: #f3da35' {% endif %}"></span>
                <span class="fa fa-star" {% if course_detail_review.averagereview > 4 %} style='color: #f3da35' {% endif %}"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {{course_detail_review.averagereview | stringformat:".2f"}}
            </div>

    </div>

{% endblock content %}

edu/courses/templates/courses/course/detail.html
{% extends "base.html" %}

{% block title %}
  {{ object.title }}
{% endblock %}

{% block content %}
  {% with subject=object.subject %}
    <h1>
      {{ object.title }}
    </h1>
    <div class="module">
      <h2>Overview</h2>
      <p>
        <a href="{% url 'courses:course_list_subject' subject.slug %}">
        {{ subject.title }}</a>.
        {{ object.modules.count }} modules.
        Instructor: {{ object.owner.get_full_name }}
      </p>
      {{ object.overview|linebreaks }}
      {% if request.user.is_authenticated and user.groups.all.0.name != 'Instructors' %}
        <!--<form action="{% url 'students:student_enroll_course' %}" method="post">
          {{ enroll_form }}
          {% csrf_token %}
          <input type="submit" value="Enroll now">
        </form> -->
        <form action="{% url 'cart:cart_add' course.id %}" method="post">
          {{ cart_course_form }}
          {% csrf_token %}
          <input type="submit" value="Add to cart">
        </form>
      {% elif user.groups.all.0.name != 'Instructors' %}
        <a href="{% url 'account_signup' %}" class="button">
          Register to enroll
        </a>
      {% endif %}
    </div>
  {% endwith %}
{% endblock %}

edu/courses/templates/courses/course/detail_for_review.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  {{ object.title }}
{% endblock %}

{% block content %}
  {% with subject=object.subject %}
    <h1>
      {{ object.title }}
    </h1>
    <div class="module">
      <h2>Overview</h2>
      <p>
        <a href="{% url 'courses:course_list_subject' subject.slug %}">
        {{ subject.title }}</a>.
        {{ object.modules.count }} modules.
        Instructor: {{ object.owner.get_full_name }}
      </p>
      {{ object.overview|linebreaks }}
      {% if request.user.is_authenticated and user.groups.all.0.name != 'Instructors' %}
        <!--<form action="{% url 'students:student_enroll_course' %}" method="post">
          {{ enroll_form }}
          {% csrf_token %}
          <input type="submit" value="Enroll now">
        </form> -->
        <form action="{% url 'courses:course_review' course.id %}" method="post"> 
          {% csrf_token %}
          {{ course_review_form|crispy }}
          <input type="submit" value="Make Review">
        </form>
      {% elif user.groups.all.0.name != 'Instructors' %}
        <a href="{% url 'account_signup' %}" class="button">
          Register to enroll
        </a>
      {% endif %}
    </div>
  {% endwith %}
{% endblock %}

edu/courses/templates/courses/course/list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
  {% if subject %}
    {{ subject.title }} courses
  {% else %}
    All courses
  {% endif %}
{% endblock %}

{% block content %}
  <h1>
    {% if subject %}
      {{ subject.title }} courses
    {% else %}
      {% trans "All courses" %}
    {% endif %}
  </h1>
  <div class="contents">
    <h3 style="color:#fff">{% trans "Subjects" %}</h3>
    <ul id="modules">
      <li {% if not subject %}class="selected"{% endif %}>
        <a href="{% url 'courses:course_list' %}">{% trans "All" %}</a>
      </li>
      {% for s in subjects %}
        <li {% if subject == s %}class="selected"{% endif %}>
          <a href="{% url 'courses:course_list_subject' s.slug %}">
            {{ s.title }}
            <br><span>{{ s.total_courses }} courses</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div class="module">
    {% for course in courses %}
      {% with subject=course.subject %}
        <h3>
          <a href="{% url 'courses:course_detail' course.slug %}">
            <span> <img src="{{ course.image.url }}" class="img-fluid" alt="" style="width:10%"></span> {{ course.title }}
          </a>
        </h3>
        <p>
          <a href="{% url 'courses:course_list_subject' subject.slug %}">{{ subject }}</a>.
            {{ course.total_modules }} modules.
            Instructor: {{ course.owner.get_full_name }}
        </p>
      {% endwith %}
    {% endfor %}
  </div>
{% endblock %}

edu/courses/templates/courses/course/rated_course.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block content %}

    <div class="container-fluid">
            <h4>You rated course: {{ reviewed_course.course.title }}</h4> 
            <p>Subject: {{ reviewed_course.subject }}</p>
            <p>Comment: {{ reviewed_course.comment }}</p>
            <p>Rate = {{ reviewed_course.rate }}</p>
        
            <div class="review-feedback">
                    {% if reviewed_course.rate == 5 %}
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                    {% elif reviewed_course.rate == 4 %}
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star"></span>
                    {% elif reviewed_course.rate == 3 %} 
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span> 
                    {% elif reviewed_course.rate == 2 %} 
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span> 
                    {% else %}
                        <span class="fa fa-star" style='color: #f3da35'></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span> 
                    {% endif %}
                    
            </div>
    </div>

{% endblock content %}